dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    secure: nwZ+FRHuI1OoX5rijM+mAezTQZrPc1rX5mgMCFCgmwXCch3J4yJ7BU42fnZDb24I6OQZTaToSQHnXhEKSm8NvPGWd3/FoAzUTsDglLbfCtder6xHKD8r6xkDMBJ4oMPm/hV05DBrcadzHtIxgK6GJZ1F4+5iXs8Pexu48H78XjDRVflvkxMCXhEPeGeVA9SDjuCYB967Mby1FS2dzde1VQrHhgLXMcmNRRkY6/akMvx0f2hUNTAaCzgCTz9OV8+YvY2DCr0GVmoxOA1bjAFdprjtslwRztWuTj7TdVsaZKnemfvbjAR9efDvGw7unGk+cKvm2MJUbkeMUKz6JB0dXLJAAOuofnIONysqF8LCTG9jVoh298fiOk7HotTzCMusO5arlJxfGJA9Wt5yqJ7DLMJc6LW8NEZKeiHNGz2TRA4eXNIZyGb2n0ixs9BzAxUsfJlwBT+MN6A9th1fN/oUQ8wsQ+IKzrTWa4FpGzZ8i9mVnhbDib5zQH74MFlGOWnlY1JK5a7tyJh6MW6qLAWXNh9mb02PzI/7ZbBCmUsd51zS/e7cxWkHwY2IBzWdyEzhk76BOlaFEjbYzDk5ukTjdqA8Ra3pV/rtVo4YkEdpuelIKxEcVp75deNTujwgH0pHdFDo/L/Ea1TzMLnnHkrofhTmyCuvkgSPY4mxlZTuJAc=
